spring:
  application:
    name: topsoil-seeder-spring-boot-sample

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true

topsoil:
  seeder:
    base-package: "io.github.mgluizbrito.topsoil_seeder.spring_boot.sample.model"
    seed-folder: h2-seeds
    enabled: true