package io.github.mgluizbrito.topsoil_seeder.yaml;

import io.github.mgluizbrito.topsoil_seeder.exception.ReferenceNotFound;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Resolves inter-entity references defined in YAML files.
 * It maintains a registry of temporary YAML IDs mapping to the actual
 * primary keys generated by the database, allowing relationship linkage.
 */
public class ReferenceResolver {

    private final Map<String, Object> idRegistry = new HashMap<>();

    /**
     * Registers a temporary YAML ID to its corresponding real database ID.
     *
     * @param yamlId The temporary ID defined in the YAML file (e.g., "user-1").
     * @param realId The actual ID generated by the database after persistence.
     */
    public void registerReference(String yamlId, Object realId) {
        idRegistry.put(yamlId, realId);
    }

    /**
     * Recursively traverses the parsed YAML data. If it encounters a String
     * starting
     * with an "@" symbol (e.g., "@user-1"), it resolves that reference by replacing
     * the
     * string with the actual real database ID from the registry.
     *
     * @param data The parsed YAML data map or list to be resolved.
     * @throws ReferenceNotFound if a reference cannot be found in the registry.
     */
    @SuppressWarnings("unchecked")
    public void resolveReferences(Object data) {

        if (data instanceof Map)
            this.resolveMapRefences((Map<String, Object>) data);
        if (data instanceof List)
            this.resolveListRefences((List<Object>) data);
    }

    private void resolveMapRefences(Map<String, Object> map) {

        for (Map.Entry<String, Object> entry : map.entrySet()) {
            Object value = entry.getValue();

            if (value instanceof String str && str.startsWith("@")) {
                String yamlId = str.substring(1); // Remove the "@"

                if (!idRegistry.containsKey(yamlId))
                    throw new ReferenceNotFound(yamlId);
                entry.setValue(idRegistry.get(yamlId));

            } else {
                resolveReferences(value);
            }
        }
    }

    private void resolveListRefences(List<Object> list) {

        for (int i = 0; i < list.size(); i++) {
            Object item = list.get(i);

            if (item instanceof String str && str.startsWith("@")) {
                String yamlId = str.substring(1);

                if (!idRegistry.containsKey(yamlId))
                    throw new ReferenceNotFound(yamlId);
                list.set(i, idRegistry.get(yamlId));

            } else {
                resolveReferences(item);
            }
        }

    }
}
